# HeyStive Voice Configuration
# Persian/Farsi Text-to-Speech Settings

voice:
  # Global voice settings
  enabled: true
  default_engine: "kamtera_female"
  auto_select_best: true
  
  # Audio settings
  audio:
    sample_rate: 22050
    output_format: "wav"
    volume: 0.8
    speed: 1.0
    output_directory: "/workspace/heystive_audio_output"
  
  # Engine configurations
  engines:
    kamtera_female:
      model_path: "Kamtera/persian-tts-female-vits"
      enabled: true
      quality: "premium"
      voice_type: "female"
      accent: "persian"
      priority: 1
      
    kamtera_male:
      model_path: "Kamtera/persian-tts-male-vits"
      enabled: true
      quality: "high"
      voice_type: "male"
      accent: "persian"
      priority: 2
      
    informal_persian:
      model_path: "karim23657/persian-tts-female-GPTInformal-Persian-vits"
      enabled: true
      quality: "high"
      voice_type: "female"
      accent: "informal_persian"
      priority: 3
      
    google_tts:
      model_path: "Persian (fa) via gtts"
      enabled: true
      quality: "high"
      voice_type: "neutral"
      accent: "persian"
      priority: 4
      requires_internet: true
      
    system_tts:
      model_path: "pyttsx3 with Persian optimization"
      enabled: true
      quality: "medium"
      voice_type: "system"
      accent: "system_default"
      priority: 5
      
    espeak_persian:
      model_path: "eSpeak-NG Persian fallback"
      enabled: true
      quality: "basic"
      voice_type: "synthetic"
      accent: "persian"
      priority: 6
  
  # Text processing settings
  text_processing:
    normalize_digits: true
    normalize_persian_chars: true
    remove_extra_spaces: true
    max_text_length: 1000
  
  # Performance settings
  performance:
    cache_models: true
    parallel_processing: false
    memory_limit_mb: 2048
    timeout_seconds: 30
  
  # User preferences
  user_preferences:
    preferred_voice: "kamtera_female"
    volume_level: 0.8
    speech_rate: 1.0
    auto_play: true
    save_audio_files: true