name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install pytest requests
      - run: nohup python server/main.py > server.log 2>&1 &
      - run: |
          for i in {1..60}; do
            curl -fsS http://127.0.0.1:8765/healthz && exit 0 || true
            sleep 2
          done
          exit 1
      - run: pytest -q