name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv && . .venv/bin/activate && pip install -r heystive_professional/requirements-core.txt && pip install -r ui_modern_web/requirements-web.txt
      - run: . .venv/bin/activate && python -m pip install pytest
      - run: . .venv/bin/activate && pytest -q